export const ADD_REQUEST="ADD_REQUEST";
export const DELETE_REQUEST="DELETE_REQUEST";
export const SEARCH_REQUEST="SEARCH_REQUEST";

export const DELETE_CLIENT="DELETE_CLIENT";
export const DELETE_TRANSPORTER="DELETE_TRANSPORTER";

export const ADD_CLIENT="ADD_CLIENT";
export const ADD_TRANSPORTER="ADD_TRANSPORTER";

export const ADD_QUOTE="ADD_QUOTE";
export const DELETE_QUOTE="DELETE_QUOTE";
